[package]
name = "brotli-rs-native"
version = "0.1.0"
authors = ["Wojciech \"Zarazek\" Wiśniewski <balagane@op.pl>"]

[dependencies]
lazy_static = "0.2.2"
crc = "1.4.0"
brotli2 = "0.2.1"

[profile.release]
debug = true

[profile.test]
debug = true
opt-level = 3
lto = true
